name: martin_upload_file_app
description: This is my app testing for uploading multitple image with quee and internet interupt 

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  loading_indicator: ^3.0.2
  dotted_border: ^2.0.0+1
  iconsax: ^0.0.8
  file_picker: ^4.1.6
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
